function darkmode() {
  document.getElementById('h1').style.color = 'black';
  document.getElementById('h2').style.color = 'black';
  document.getElementById('h22').style.color = 'black';
  document.getElementById('h3').style.color = 'black';
  document.getElementById('h32').style.color = 'black';
  document.getElementById('span1').style.color = 'mediumspringgreen';
  document.getElementById('span1').style.backgroundColor = 'black';
  document.getElementById('youhavechosen').style.color = 'black';
  document.getElementById('body').style.backgroundColor = 'black';
  document.getElementById('h2').style.backgroundColor = 'purple';
  document.getElementById('h22').style.backgroundColor = 'purple';
  document.getElementById('h1').style.backgroundColor = 'navy';
  document.getElementById('h3').style.backgroundColor = 'green';
  document.getElementById('h32').style.backgroundColor = 'green';
  document.getElementById('audiobutton1').style.backgroundColor = 'blue';
  document.getElementById('audiobutton2').style.backgroundColor = 'blue';
  document.getElementById('audiobutton3').style.backgroundColor = 'blue';
  document.getElementById('audiobutton4').style.backgroundColor = 'blue';
  document.getElementById('audiobutton5').style.backgroundColor = 'blue';
  document.getElementById('youhavechosen').style.borderTop = '15px solid aqua';
  document.getElementById('youhavechosen').style.borderBottom = '15px solid darkcyan';
  document.getElementById('youhavechosen').style.borderLeft = '15px solid mediumturquoise';
  document.getElementById('youhavechosen').style.borderRight = '15px solid mediumturquoise';
  document.getElementById('youhavechosen').style.background = 'lightseagreen';
  document.getElementById('audiobutton1').style.border = '3px solid limegreen';
  document.getElementById('audiobutton2').style.border = '3px solid limegreen';
  document.getElementById('audiobutton3').style.border = '3px solid limegreen';
  document.getElementById('audiobutton4').style.border = '3px solid limegreen';
  document.getElementById('audiobutton5').style.border = '3px solid limegreen';
};

function firelightmode() {
  document.getElementById('h1').style.color = 'black';
  document.getElementById('h2').style.color = 'black';
  document.getElementById('h22').style.color = 'black';
  document.getElementById('h3').style.color = 'black';
  document.getElementById('h32').style.color = 'black';
  document.getElementById('body').style.backgroundColor = 'white';
  document.getElementById('h2').style.backgroundColor = 'gold';
  document.getElementById('h22').style.backgroundColor = 'gold';
  document.getElementById('h1').style.backgroundColor = 'yellow';
  document.getElementById('h3').style.backgroundColor = 'goldenrod';
  document.getElementById('h32').style.backgroundColor = 'goldenrod';
  document.getElementById('audiobutton1').style.backgroundColor = 'orange';
  document.getElementById('audiobutton2').style.backgroundColor = 'orange';
  document.getElementById('audiobutton3').style.backgroundColor = 'orange';
  document.getElementById('audiobutton4').style.backgroundColor = 'orange';
  document.getElementById('youhavechosen').style.borderTop = '15px solid firebrick';
  document.getElementById('youhavechosen').style.borderBottom = '15px solid crimson';
  document.getElementById('youhavechosen').style.borderLeft = '15px solid red';
  document.getElementById('youhavechosen').style.borderRight = '15px solid red';
  document.getElementById('youhavechosen').style.background = 'salmon';
  document.getElementById('span1').style.color = 'crimson';
  document.getElementById('span1').style.backgroundColor = 'white';
  document.getElementById('youhavechosen').style.color = 'black';
  document.getElementById('audiobutton1').style.border = '3px solid hotpink';
  document.getElementById('audiobutton2').style.border = '3px solid hotpink';
  document.getElementById('audiobutton3').style.border = '3px solid hotpink';
  document.getElementById('audiobutton4').style.border = '3px solid hotpink';
};

function discordlightmode() {
  document.getElementById('h1').style.color = 'ghostwhite';
  document.getElementById('h2').style.color = 'ghostwhite';
  document.getElementById('h22').style.color = 'ghostwhite';
  document.getElementById('h3').style.color = 'ghostwhite';
  document.getElementById('h32').style.color = 'ghostwhite';
  document.getElementById('body').style.backgroundColor = 'white';
  document.getElementById('h2').style.backgroundColor = 'white';
  document.getElementById('h22').style.backgroundColor = 'white';
  document.getElementById('h1').style.backgroundColor = 'white';
  document.getElementById('h3').style.backgroundColor = 'white';
  document.getElementById('h32').style.backgroundColor = 'white';
  document.getElementById('audiobutton1').style.backgroundColor = 'white';
  document.getElementById('audiobutton2').style.backgroundColor = 'white';
  document.getElementById('audiobutton3').style.backgroundColor = 'white';
  document.getElementById('audiobutton4').style.backgroundColor = 'white';
  document.getElementById('youhavechosen').style.borderTop = '15px solid white';
  document.getElementById('youhavechosen').style.borderBottom = '15px solid white';
  document.getElementById('youhavechosen').style.borderLeft = '15px solid white';
  document.getElementById('youhavechosen').style.borderRight = '15px solid white';
  document.getElementById('youhavechosen').style.background = 'ghostwhite';
  document.getElementById('span1').style.color = 'ghostwhite';
  document.getElementById('span1').style.backgroundColor = 'white';
  document.getElementById('youhavechosen').style.color = 'ghostwhite';
  document.getElementById('audiobutton1').style.border = '3px solid white';
  document.getElementById('audiobutton2').style.border = '3px solid white';
  document.getElementById('audiobutton3').style.border = '3px solid white';
  document.getElementById('audiobutton4').style.border = '3px solid white';
  confirm('You are an idiot for using discord light mode');
};

function gaymode() {
  document.getElementById('h1').style.color = 'black';
  document.getElementById('h2').style.color = 'black';
  document.getElementById('h22').style.color = 'black';
  document.getElementById('h3').style.color = 'black';
  document.getElementById('h32').style.color = 'black';
  document.getElementById('span1').style.color = 'black';
  document.getElementById('span1').style.backgroundColor = 'yellow';
  document.getElementById('body').style.backgroundColor = 'white';
  document.getElementById('h2').style.backgroundColor = 'orange';
  document.getElementById('h22').style.backgroundColor = 'blue';
  document.getElementById('h1').style.backgroundColor = 'red';
  document.getElementById('h3').style.backgroundColor = 'blue';
  document.getElementById('h32').style.backgroundColor = 'purple';
  document.getElementById('audiobutton1').style.backgroundColor = 'green';
  document.getElementById('audiobutton2').style.backgroundColor = 'green';
  document.getElementById('audiobutton3').style.backgroundColor = 'green';
  document.getElementById('audiobutton4').style.backgroundColor = 'green';
  document.getElementById('youhavechosen').style.borderTop = '15px solid aqua';
  document.getElementById('youhavechosen').style.borderBottom = '15px solid aqua';
  document.getElementById('youhavechosen').style.borderLeft = '15px solid aqua';
  document.getElementById('youhavechosen').style.borderRight = '15px solid aqua';
  document.getElementById('youhavechosen').style.background = 'aqua';
  document.getElementById('youhavechosen').style.color = 'black';
  document.getElementById('audiobutton1').style.border = '3px solid green';
  document.getElementById('audiobutton2').style.border = '3px solid green';
  document.getElementById('audiobutton3').style.border = '3px solid green';
  document.getElementById('audiobutton4').style.borderRight = '1px solid green';
  alert('If you\'re gay, then don\'t worry, you\'re loved. But not by me of course, I\'m not gay');
};

function backin1969mode() {
  document.getElementById('h1').style.color = 'black';
  document.getElementById('h2').style.color = 'black';
  document.getElementById('h22').style.color = 'black';
  document.getElementById('h3').style.color = 'black';
  document.getElementById('h32').style.color = 'black';
  document.getElementById('body').style.backgroundColor = 'smokewhite';
  document.getElementById('h2').style.backgroundColor = 'lightgrey';
  document.getElementById('h22').style.backgroundColor = 'grey';
  document.getElementById('h1').style.backgroundColor = 'gainsboro';
  document.getElementById('h3').style.backgroundColor = 'grey';
  document.getElementById('h32').style.backgroundColor = 'grey';
  document.getElementById('audiobutton1').style.backgroundColor = 'silver';
  document.getElementById('audiobutton2').style.backgroundColor = 'silver';
  document.getElementById('audiobutton3').style.backgroundColor = 'silver';
  document.getElementById('audiobutton4').style.backgroundColor = 'silver';
  document.getElementById('youhavechosen').style.borderTop = '15px solid grey';
  document.getElementById('youhavechosen').style.borderBottom = '15px solid slategrey';
  document.getElementById('youhavechosen').style.borderLeft = '15px solid dimgrey';
  document.getElementById('youhavechosen').style.borderRight = '15px solid dimgrey';
  document.getElementById('youhavechosen').style.background = 'darkgrey';
  document.getElementById('span1').style.color = 'black';
  document.getElementById('span1').style.backgroundColor = 'grey';
  document.getElementById('youhavechosen').style.color = 'black';
  document.getElementById('audiobutton1').style.border = '3px solid black';
  document.getElementById('audiobutton2').style.border = '3px solid black';
  document.getElementById('audiobutton3').style.border = '3px solid black';
  document.getElementById('audiobutton4').style.border = '3px solid black';
}
